language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
  - "6.0"
  - "7.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/720cf5e1ee34248a801d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
addons:
  code_climate:
    repo_token:
      secure: "K+xWBLPNO6lgA+nwvNVDnWHJBwnlC9g1UCDRDjKD1jM5F1X0XiroLjFEWQXMmWdNVTQ49KY3SdJ3cRxtGLcHnGbHQ+fXSlqclY2KEl9A0Pc9EtO9u/ZGdbM7jW6KBW7JRW9GpEoeZl8XY3zYqLOM0ODe6mf30eONqSLppDZJOPk="
